python : System check identified some issues:
En línea: 1 Carácter: 1
+ python manage.py check_coca_cola 2>&1 | 
Out-File -FilePath coca_outpu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified:  
   (System check identified some issues::St  
  ring) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandE 
   rror
 

WARNINGS:
<django.template.backends.django.DjangoTempla
tes object at 0x00000281DA3FB0E0>: 
(templates.W003) 'format_filters' is used 
for multiple template tag modules: 
'tesoreria.templatetags.format_filters', 
'usuarios.templatetags.format_filters', 
'ventas.templatetags.format_filters'

=== COCA COLA 350ML ===
ID: 15
Precio Venta: $1200
Traceback (most recent call last):
  File 
"C:\PROJECTOS-WEB\GestionCloud\manage.py", 
line 22, in <module>
    main()
    ~~~~^^
  File 
"C:\PROJECTOS-WEB\GestionCloud\manage.py", 
line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Progra
ms\Python\Python313\Lib\site-packages\django\
core\management\__init__.py", line 442, in 
execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Progra
ms\Python\Python313\Lib\site-packages\django\
core\management\__init__.py", line 436, in 
execute
    self.fetch_command(subcommand).run_from_a
rgv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Progra
ms\Python\Python313\Lib\site-packages\django\
core\management\base.py", line 413, in 
run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Progra
ms\Python\Python313\Lib\site-packages\django\
core\management\base.py", line 459, in 
execute
    output = self.handle(*args, **options)
  File "C:\PROJECTOS-WEB\GestionCloud\ventas\
management\commands\check_coca_cola.py", 
line 15, in handle
    self.stdout.write(f"Precio Final: 
${coca.precio_final_calculado}")
                                        
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Articulo' object has no 
attribute 'precio_final_calculado'
